SELECT * FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END
FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END,
AVG([PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END

SELECT YEAR(DATA), COUNT(*) AS 'NFS POR ANO' FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)
ORDER BY YEAR(DATA)

SELECT CPF, 
CASE WHEN [PRIMEIRA COMPRA]  = 1 THEN 'JÁ É CLIENTE' 
	 ELSE 'PROSPECTAR' END AS 'COMPROU/NÃO COMPROU'
FROM [dbo].[TABELA DE CLIENTES]
ORDER BY 'COMPROU/NÃO COMPROU' DESC


SELECT NOME, [DATA DE NASCIMENTO],
	CASE 
	WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTO'
	WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVEM'
	ELSE 'CRIANÇA' END AS 'CLASSIFICAÇÃO'
FROM[dbo].[TABELA DE CLIENTES]
ORDER BY YEAR([DATA DE NASCIMENTO])