SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Laranja'

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]
[PREÇO]

SELECT DISTINCT [CODIGO DO PRODUTO], SUM([QUANTIDADE] * [PREÇO] ) AS TOTAL, [CODIGO DO PRODUTO], [QUANTIDADE], [PREÇO]  FROM [dbo].[ITENS NOTAS FISCAIS] 
GROUP BY [CODIGO DO PRODUTO], [QUANTIDADE], [PREÇO]
