
SELECT CEILING(12.333223)

SELECT FLOOR(12.333223)

SELECT RAND()

SELECT ROUND(12.33323323, 2)

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PREÇO], FORMAT(ROUND(([QUANTIDADE] * [PREÇO]),1), 'C', 'pt-br') FROM [ITENS NOTAS FISCAIS]


select ROUND(SQRT([QUANTIDADE]), 2) from [ITENS NOTAS FISCAIS]