CREATE DATABASE USE VENDPOLPAS

CREATE TABLE PRODUTOS(
CODIGO VARCHAR(10) NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
SABOR VARCHAR(50) NOT NULL,
EMBALAGEM VARCHAR(50) NOT NULL,
PRECO MONEY NOT NULL
CONSTRAINT PK_PRODUTOS PRIMARY KEY CLUSTERED(CODIGO) 
)

CREATE TABLE VENDEDORES (
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DT_ADMIDDAO DATE NULL,
FERIAS BIT NULL,
CONSTRAINT PK_VENDEDORES PRIMARY KEY CLUSTERED(MATRICULA)
)

CREATE TABLE CLIENTES(
COD_CLIENTE VARCHAR(5),
CPF VARCHAR(11) UNIQUE NOT NULL,
ENDERECO VARCHAR(150) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DT_NASCIMENTO DATE NULL,
IDADE SMALLINT NULL,
SEXO VARCHAR(1) NULL,
LIMITE_CREDITO MONEY NULL,
VOLUME_COMPRA FLOAT NULL, 
PRIMEIRA_COMPRA BIT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY CLUSTERED(COD_CLIENTE)
)

CREATE TABLE VENDAS (
NF_NUMERO VARCHAR(5) NOT NULL,
DT_VENDA DATE,
COD_CLIENTE VARCHAR(5) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO MONEY,
CONSTRAINT FK_NOTAS_CLIENTES FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE),
CONSTRAINT FK_NOTAS_VENDEDOR FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA)
)

--ALTER TABLE VENDAS
--WITH CHECK ADD CONSTRAINT FK_NOTAS_CLIENTES
--FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE)

--PersonID int FOREIGN KEY REFERENCES Persons(PersonID)

/*
Número (PK) e (FK - Tabela de Vendas) - Varchar(5)
Código Produto (FK - Tabela de Produtos) - Varchar(10)
Quantidade - Int32
Preço - Float
*/

CREATE TABLE ITENS_VENDIDOS(
NF_NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE SMALLINT NOT NULL,
PRECO MONEY NOT NULL,
CONSTRAINT FK_ITENS_VENDIDOS_VENDAS FOREIGN KEY(NF_NUMERO) REFERENCES VENDAS(NF_NUMERO)

)