SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO 
HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS 'SOMA DA LISTA', MAX([PREÇO DE LISTA]) AS 'MAIOR PREÇO', MIN([PREÇO DE LISTA]) AS 'MENOR PREÇO' 
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS 'MAIOR PREÇO', MIN([PREÇO DE LISTA])AS 'MENOR PREÇO' FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]), MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [dbo].[TABELA DE CLIENTES] GROUP BY ESTADO
HAVING SUM([LIMITE DE CREDITO]) >=850000

