SELECT NOME, 
	   BAIRRO 
FROM [TABELA DE CLIENTES]

SELECT NOME, 
	   BAIRRO 
FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO 
				 FROM [TABELA DE VENDEDORES])

SELECT EMBALAGEM,
	   MAX([PREÇO DE LISTA]) 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

CREATE VIEW uVW_CONSULTA_EMBALAGENS
AS
SELECT NOVA_CONSULTA.EMBALAGEM,
	   NOVA_CONSULTA.MAX_PRECO
FROM (SELECT EMBALAGEM,
	         MAX([PREÇO DE LISTA]) AS MAX_PRECO 
	  FROM [TABELA DE PRODUTOS] 
	  GROUP BY EMBALAGEM)AS NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <= 5

SELECT * FROM uVW_CONSULTA_EMBALAGENS

SELECT EMBALAGEM,
	   MAX([PREÇO DE LISTA]) AS MAX_PRECO 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT * FROM [dbo].[VW_EMBALAGENS]

SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PRECO
FROM VW_EMBALAGENS AS NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <= 5

CREATE VIEW uVW_CLIENTES
AS
SELECT CPF,
	   NOME
FROM [TABELA DE CLIENTES]

SELECT * FROM uVW_CLIENTES

SP_HELPTEXT uVW_CLIENTES
	   